name: Build & Publish Tangerine Docker Images

on:
  push:
    tags:
      - 'v*'

env:
  DOCKER_USER: albjo

jobs:
  couchdb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ env.DOCKER_USER }} --password-stdin
      - run: docker build -f dockerhub/Dockerfile.couchdb -t ${{ env.DOCKER_USER }}/tangerine-couchdb:${{ github.ref_name }} -t ${{ env.DOCKER_USER }}/tangerine-couchdb:latest .
      - run: docker push ${{ env.DOCKER_USER }}/tangerine-couchdb:${{ github.ref_name }}
      - run: docker push ${{ env.DOCKER_USER }}/tangerine-couchdb:latest

  server:
    needs: couchdb
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ env.DOCKER_USER }} --password-stdin
      - run: docker build -f dockerhub/Dockerfile.server -t ${{ env.DOCKER_USER }}/tangerine-server:${{ github.ref_name }} -t ${{ env.DOCKER_USER }}/tangerine-server:latest .
      - run: docker push ${{ env.DOCKER_USER }}/tangerine-server:${{ github.ref_name }}
      - run: docker push ${{ env.DOCKER_USER }}/tangerine-server:latest

  server-ui:
    needs: server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ env.DOCKER_USER }} --password-stdin
      - run: docker build -f dockerhub/Dockerfile.server-ui -t ${{ env.DOCKER_USER }}/tangerine-server-ui:${{ github.ref_name }} -t ${{ env.DOCKER_USER }}/tangerine-server-ui:latest .
      - run: docker push ${{ env.DOCKER_USER }}/tangerine-server-ui:${{ github.ref_name }}
      - run: docker push ${{ env.DOCKER_USER }}/tangerine-server-ui:latest

  apk-generator:
    needs: server-ui
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ env.DOCKER_USER }} --password-stdin
      - run: docker build -f dockerhub/Dockerfile.apk-generator -t ${{ env.DOCKER_USER }}/tangerine-apk-generator:${{ github.ref_name }} -t ${{ env.DOCKER_USER }}/tangerine-apk-generator:latest .
      - run: docker push ${{ env.DOCKER_USER }}/tangerine-apk-generator:${{ github.ref_name }}
      - run: docker push ${{ env.DOCKER_USER }}/tangerine-apk-generator:latest
