name: Build & Publish Tangerine Docker Images

on:
  push:
    tags:
      - 'v*'

env:
  DOCKER_USER: albjo

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        run: docker buildx create --use

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ env.DOCKER_USER }} --password-stdin

      - name: Build & Push couchdb
        run: |
          docker buildx build \
            -f dockerhub/Dockerfile.couchdb \
            -t ${{ env.DOCKER_USER }}/tangerine-couchdb:${{ github.ref_name }} \
            -t ${{ env.DOCKER_USER }}/tangerine-couchdb:latest \
            --platform linux/amd64 \
            --push \
            .

      - name: Build & Push server
        run: |
          docker buildx build \
            -f dockerhub/Dockerfile.server \
            -t ${{ env.DOCKER_USER }}/tangerine-server:${{ github.ref_name }} \
            -t ${{ env.DOCKER_USER }}/tangerine-server:latest \
            --platform linux/amd64 \
            --push \
            .

      - name: Build & Push server-ui
        run: |
          docker buildx build \
            -f dockerhub/Dockerfile.server-ui \
            -t ${{ env.DOCKER_USER }}/tangerine-server-ui:${{ github.ref_name }} \
            -t ${{ env.DOCKER_USER }}/tangerine-server-ui:latest \
            --platform linux/amd64 \
            --push \
            .

      - name: Build & Push apk-generator
        run: |
          docker buildx build \
            -f dockerhub/Dockerfile.apk-generator \
            -t ${{ env.DOCKER_USER }}/tangerine-apk-generator:${{ github.ref_name }} \
            -t ${{ env.DOCKER_USER }}/tangerine-apk-generator:latest \
            --platform linux/amd64 \
            --push \
            .
